### ISSUE TITLE
What does option --vcf do

### ISSUE THREAD

**Issue by yaohaobin** [philres/nextgenmap-lr#2]
I am trying ngm-lr for sv detection and interested in option --vcf. What does it mean? Thanks!

**Comment by philres** [comment]
Hi!

--vcf allows the user to specify a list of SNPs that will be taken into account while mapping. It was introduced to avoid mapping biases caused by e.g. allele specific differences. In the context of long read mapping for structural variation calling it is not really relevant. We will most probably remove/deactivate it with the next update.

If you are interested in generating variant calls from ngmlr alignments I would recommend using Sniffles (https://github.com/fritzsedlazeck/Sniffles).

I hope that answered your question. Please let me know if you have any other questions or suggestions.

Thanks,
Philipp
